novel/urls.py
"""定义novel的URL模式"""

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'novel_content/(?P<novelid>\d+)/$', views.detail, name='novel_content'),
    url(r'chapter/(?P<chapterid>\d+)/$', views.chapter, name='chapter'),
    url(r'sort_list/(?P<type>\d+)/(?P<page>\d+)/$', views.more, name='sort_list'),
    url(r'search/$', views.search, name='search')
]

novelproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('novel.urls', namespace='novel'))
]

novel/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class Chapter(models.Model):
    chapterid = models.AutoField(primary_key=True)
    novelid = models.ForeignKey('Novel', models.DO_NOTHING, db_column='novelid')
    title = models.CharField(max_length=100)
    content = models.TextField()

    class Meta:
        managed = False
        db_table = 'chapter'


class ChapterCopy(models.Model):
    chapterid = models.AutoField(primary_key=True)
    novelid = models.ForeignKey('NovelCopy', models.DO_NOTHING, db_column='novelid')
    title = models.CharField(max_length=100)
    content = models.TextField()

    class Meta:
        managed = False
        db_table = 'chapter_copy'


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class Novel(models.Model):
    novelid = models.AutoField(primary_key=True)
    type = models.IntegerField()
    novelname = models.CharField(max_length=100)
    novelimg = models.CharField(max_length=100)
    description = models.TextField()
    state = models.CharField(max_length=20)
    author = models.CharField(max_length=20)

    class Meta:
        managed = False
        db_table = 'novel'


class NovelCopy(models.Model):
    novelid = models.AutoField(primary_key=True)
    type = models.IntegerField()
    sort = models.CharField(max_length=100)
    novelname = models.CharField(max_length=100)    #
    novelimg = models.CharField(max_length=100)     #
    description = models.TextField()                #
    state = models.CharField(max_length=20)
    author = models.CharField(max_length=20)        #

    class Meta:
        managed = False
        db_table = 'novel_copy'

novel/views.py
from django.shortcuts import render
from django.http import HttpResponse
from novel.models import NovelCopy, ChapterCopy
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def index(request):
    novelcopys = NovelCopy.objects.filter().order_by('?')[:4]
    hotnovelcopys = NovelCopy.objects.filter().order_by('novelid')[:5]
    xuanhuannovels = NovelCopy.objects.filter(sort="玄幻").order_by('?')[:6]
    wuxianovels = NovelCopy.objects.filter(sort="武侠").order_by('?')[:6]
    context = {'novelcopys': novelcopys, 'xuanhuannovels': xuanhuannovels,
               'wuxianovels': wuxianovels, 'hotnovelcopys': hotnovelcopys}
    return render(request, 'index.html', context)

def detail(request, novelid):
    chaptercopys = ChapterCopy.objects.filter(novelid=novelid)
    novelcopy = NovelCopy.objects.get(novelid=novelid)
    context = {'chaptercopys': chaptercopys, 'novelcopy': novelcopy}
    return render(request, 'detail.html', context)

def chapter(request, chapterid):
    chaptertitle = ChapterCopy.objects.get(chapterid=chapterid) # ChapterCopy Object
    chapters = ChapterCopy.objects.filter(novelid=chaptertitle.novelid) # QuerySet
    nextchapter = int(chapterid) + 1
    lastchapter = int(chapterid) - 1
    if lastchapter == 0:
        lastchapter = 1
    # 获取当前ChapterCopy的Queryset，并提取novelid的值（一个tuple），这里novelid都是一样的，取一个即可
    chapter_query = chapters.values_list('novelid')[0]
    thenovelid = chapter_query[0]     #提取tuple中的数值，即小说的id
    thenovelname = NovelCopy.objects.get(novelid=thenovelid)
    context = {'chaptertitle': chaptertitle,'chapters': chapters, 'thenovelid': thenovelid,
               'lastchapter': lastchapter, 'nextchapter': nextchapter, 'thenovelname': thenovelname}
    return render(request, 'chapter.html', context)

def more(request, type, page):
    novellists = NovelCopy.objects.filter(type=type).order_by('novelid')  # QuerySet
    sortquery = list(novellists.values_list('sort')[0])
    novelsort = sortquery[0]
    typequery = list(novellists.values_list('type')[0])
    noveltype = typequery[0]
    paginator = Paginator(novellists, 20)   # Show 10 novels per page
    try:
        novels = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        novels = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        novels = paginator.page(paginator.num_pages)

    context = {'novellists': novellists, 'novels': novels,
               'novelsort': novelsort, 'noveltype': noveltype }
    return render(request, 'more.html', context)

def search(request):
    novelname = request.GET.get('kw')   # 获取所要搜索的小说名
    searchnovels = NovelCopy.objects.filter(novelname=novelname)    # 从数据库中查找小说
    random_recommends = NovelCopy.objects.filter().order_by('?')[:6]    # 随机抽取6本小说
    context = {'novelname': novelname, 'searchnovels': searchnovels,
               'random_recommends': random_recommends}
    return render(request, 'search.html', context)

novel/templates/chapter.html
{% load staticfiles %}
<!doctype html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta name="Keywords" content="最新,最新章节,都市小说,阅读" />
        <meta name="description" content="随身带个侏罗纪最新章节阅读，随身带个侏罗纪是一部都市小说,由木鱼和尚创作,起点提供首发更新。第四百六十一章 杀鸡儆猴 如何解释(2016.09.27)" />
        <title>{{ chaptertitle.title }}_{{ thenovelname.novelname }}_Python学院_小说下载</title>
        <link href="{% static 'css/chapter.css' %}" rel="stylesheet" />
    </head>
<body>

    <!-- Full Screen -->
    <div class="full-pic"></div>
    <!-- sidebar -->
    <div class="sidebar">
        <span class="return iconfont">&#xe618;</span>

        <!-- dire -->
        <span id="lan-Top"  class="dir">
            <span class="dir-wrap">
                <i class="iconfont">&#xe60b;</i>
                <p>目录</p>
            </span>
            <div class="dir-content" style="display: none;">
                <h3>
                    <i class="iconfont close">&#xe605;</i>
                    <span class="content-txt">目录</span>
                </h3>

                <div class="title-list">

                    <div class="title-wrap">
                        <h2>
                            <span>
                                作品相关
                                <i class="iconfont dir-icon icon-icon2"></i>
                            </span>
                        </h2>

                        <ul class="dir-list">
                            {% for chapter in chapters %}
                            <li><a href="{% url 'novel:chapter' chapter.chapterid %}">
                                {{ chapter.title }}
                            </a></li>
                            {% endfor %}
                        </ul>

                    </div>

                </div>


            </div>
        </span>
    </div>

    <!--===== Header Begin =====-->
    <header class="header">
        <div class="wrap990" style="width: auto; max-width: 990px;">
            <div class="logo">
                <a href="/">潭州Python书院</a>
            </div>

            <div class="right-search">
                <form action="{% url 'novel:search' %}" target="_blank">
                    <input name="kw" type="text" />
                    <input id="search-submit" type="submit" value="" />
                    <label class="label-tag" for="search-submit">
                        <i class="iconfont">&#xe714;</i>
                    </label>
                </form>
            </div>
           
        </div>
    </header>
    <!--===== End Header =====-->



    <!--===== Main Begin =====-->
    <section class="main">
        <div class="wrap800 main-wrap">
            <div class="content">
                <h2></h2>
                <h2>{{ chaptertitle.title }}</h2>
                <div class="read-content j_readContent">
                    <p>{{ chaptertitle.content|safe }}</p>
                </div>
            </div>
        </div>


        <div class="chapter-controll wrap800">

            <a href="{% url 'novel:chapter' lastchapter %}">上一章</a><a href="{% url 'novel:novel_content' thenovelid %}">目录</a><a href="{% url 'novel:chapter' nextchapter %}">下一章</a>

        </div>
    </section>

    <!--===== End Main =====-->



<!-- Main Plugin -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static 'js/chapter.js' %}"></script>

</body>
</html>

novel/templates/detail.html
{% load staticfiles %}
<!doctype html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="Keywords" content="" />
    <meta name="description" content="" />
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" /> -->
    <title>{{ novelcopy.novelname }} - Python探索馆 - Slice</title>
    <!-- Main Theme -->
    <link rel="stylesheet" href="{% static 'css/detail.css' %}" />

    <!-- Font -->
    <link rel="stylesheet" href="http://at.alicdn.com/t/font_n5vylbuqe61or.css" />
    <link rel="stylesheet" href="http://at.alicdn.com/t/font_s60wfkri6ndpwrk9.css">
  </head>
<body>


<!--===== Full Screen BG =====-->
<div class="full-pic"></div>



<!--===== Begin Header =====-->
<header class="header">
  <div class="fixed-head" style="z-index: 100;position: fixed; width: 100%; background-color: #3e3d43; -webkit-transform: translateZ(0);">
    <div class="wrap1000 head-wrap">

      <div class="logo">
        <a href="/">
          Python学院图书馆
        </a>
      </div>

      <!-- nav -->
      <div class="nav">
        <ul class="nav-list">
          <li>
            <a href="/"><span>首页</span></a>
          </li>
          <li>
            <a href="{% url 'novel:sort_list' 1 1 %}"><span>玄幻</span></a>
          </li>
          <li>
            <a href="{% url 'novel:sort_list' 2 1 %}"><span>武侠</span></a>
          </li>
          <li>
            <a href="{% url 'novel:sort_list' 3 1 %}"><span>历史</span></a>
          </li>
          <li>
            <a href="{% url 'novel:sort_list' 4 1 %}"><span>言情</span></a>
          </li>
        </ul>
      </div><!-- ./nav -->

      <div class="search">
        <form action="{% url 'novel:search'%}" method="get" target="_blank">
          <input name="kw" placeholder="搜索书名" class="search-inp" type="text" maxlength="10" />
          <input id="search-submit-btn" type="submit" style="display: none;" />
          <label for="search-submit-btn">
            <i class="iconfont icon-search"></i>
          </label>
        </form>
      </div>

    </div><!-- /.wrap1000 -->
  </div>
</header>
<!--===== header End =====-->



<!--===== Begin Main =====-->
<section class="main">
  <div class="main-wrap wrap1000">
    <div class="hot-section">


      <div class="hot-content">

        <div class="book-avatar">
          <img src="{{ novelcopy.novelimg }}" alt="" />
        </div>

        <div class="book-detail">
          <h1>
            <em class="mr10">{{ novelcopy.novelname }}</em>
            <span>
              <a href="javascript: void(0);">{{ novelcopy.author }}</a>
               著
            </span>
          </h1>

          <p class="book-tag">
            <span class="now-book"><i class="mr10 iconfont icon-dushi"></i>现代 / 都市</span>
            <span class="through-book">穿越</span>
          </p>
          <p class="description">
            {{ novelcopy.description|safe }}
          </p>


          <a class="now-read btn" href="{% url 'novel:chapter' 1 %}">立即阅读</a>


        </div>

      </div>
    </div>

    <!-- catalog -->
    <div class="catalog">
      <h2>目录(<span>20</span>章)</h2>

      <ul class="catalog-list">
        {% for chaptercopy in chaptercopys %}
        <li><a href="{% url 'novel:chapter' chaptercopy.chapterid %}">
          {{ chaptercopy.title }}
        </a></li>
        {% endfor %}
      </ul>
    </div><!-- /.catalog -->
  </div>
</section>
<!--===== Main End =====-->



<!--===== Begin Footer =====-->
<footer class="footer">
  <div class="wrap1000 footer-wrap">
    <div class="logo-footer">
      <a href="index.html">
        <img src="{% static 'img/head_logo.png' %}" alt="" width="55" height="50" />
        <span class="footer-txt">潭州教育Python学院</span>
      </a>
      <span class="footer-font">
        TAN ZHOU EDU PYTHON COLLEGE
      </span>
    </div>
    <div class="copy-right">
      <p>
        本站小说均来源于互联网,仅供技术学习和交流使用,请尊重原创作者切勿用商业用途,请于下载后的24小时内删除。
      </p>
      <p class="">
        Copyright © 2017 All Rights Reserved 湖南潭州教育网络科技有限公司PYTHON学院 
      </p>
    </div>
  </div>
</footer>
<!--===== Footer End =====-->



<!-- Main Plugin -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>

</body>
</html>               

novel/templates/index.html
{% load staticfiles %}
<!doctype html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="Keywords" content="" />
    <meta name="description" content="" />
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" /> -->
    <title>Python探索馆 - Slice</title>
    <!-- Main Theme -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />

    <!-- Font -->
    <link rel="stylesheet" href="http://at.alicdn.com/t/font_n5vylbuqe61or.css" />
  </head>
<body>


<!--===== Full Screen BG =====-->
<div class="full-pic"></div>



<!--===== Begin Header =====-->
<header class="header">
  <div class="fixed-head" style="position: fixed; width: 100%; background-color: #65b2f1; -webkit-transform: translateZ(0);">
    <div class="wrap1000 head-wrap">

      <div class="logo">
        <a href="/">
          Python学院图书馆
        </a>
      </div>

      <!-- nav -->
      <div class="nav">
        <ul class="nav-list">
          <li>
            <a href="/"><span>首页</span></a>
          </li>
          <li>
            <a href="{% url 'novel:sort_list' 1 1 %}"><span>玄幻</span></a>
          </li>
          <li>
            <a href="{% url 'novel:sort_list' 2 1 %}"><span>武侠</span></a>
          </li>
          <li>
            <a href="{% url 'novel:sort_list' 3 1 %}"><span>历史</span></a>
          </li>
          <li>
            <a href="{% url 'novel:sort_list' 4 1 %}"><span>言情</span></a>
          </li>
        </ul>
      </div><!-- ./nav -->

      <div class="search">
        <form action="{% url 'novel:search'%}" method="get" target="_blank">
          <input name="kw" placeholder="搜索书名" class="search-inp" type="text" value="" maxlength="10" />
          <input id="search-submit-btn" type="submit" style="display: none;" />
          <label for="search-submit-btn">
            <i class="iconfont icon-search"></i>
          </label>
        </form>
      </div>

    </div><!-- /.wrap1000 -->
  </div>
</header>
<!--===== header End =====-->



<!--===== Begin Main =====-->
<section class="main">
  <div class="main-wrap wrap1000">
    <div class="hot-section">

      <div class="hot-shadow">
        <div class="hot-title">最热</div>
      </div>
      
      <!-- figure -->
      <div class="figure"></div>

      <div class="hot-content">

        <!-- banner -->
        <div class="banner">
          <ul class="banner-imgs">
            {% for hotnovelcopy in hotnovelcopys %}
            <li>
              <a href="{% url 'novel:novel_content' hotnovelcopy.novelid %}">
                  <img src="{{ hotnovelcopy.novelimg }}" alt="" width="750" height="300" />
              </a>
            </li>
            {% endfor %}
          </ul><!-- /.imgs -->

          <div class="control-page">
            <a class="iconfont icon-bannerzuo" href="javascript: void(0);"></a>
            <a class="iconfont icon-banneryou" href="javascript: void(0);"></a>
          </div>

          <ul class="banner-btn">
            <li class="banner-btn-on"></li>
            <li></li>
            <li></li>
            <li></li>
            <li></li>
          </ul>

        </div><!-- /.banner -->




        <div class="hot-recommend">

          <ul class="hot-list">

            {% for novelcopy in novelcopys %}
            <li>
              <a href="{% url 'novel:novel_content' novelcopy.novelid %}">
                <div>
                  <img src="{{ novelcopy.novelimg }}" alt="" width="" /><span></span>
                </div>
                <p>
                  <b>{{ novelcopy.novelname }}</b>
                  <span class="author">{{ novelcopy.author }} 著</span>
                  <span class="book-description">
                    {{ novelcopy.description|safe }}
                  </span>
                </p>
              </a>
            </li>
            {% endfor %}

          </ul>

        </div><!-- /.recommend -->



        <!-- Xuanhuan -->
        <div class="xuanhuan">
          <div class="xuanhuan-title">
            <span>玄幻</span>
            <p class="txt">fantasy</p>
            <p>novel</p>
            <span class="more"><a href="{% url 'novel:sort_list' 1 1 %}">更多<span style="float: right;font-size: 12px;letter-spacing: -2px;vertical-align: middle;margin-top: 2px;">&nbsp;&gt;&gt;</span></a></span>
          </div>
          <div class="wrap890 xuanhuan-wrap">

            <ul class="book-list">

              {% for xuanhuannovel in xuanhuannovels %}
              <li class="book">
                <div class="book-wrap">
                  <a class="cover" href="{% url 'novel:novel_content' xuanhuannovel.novelid %}"><img src="{{ xuanhuannovel.novelimg }}" alt="" width="136" height="180" /></a>
                  <div class="book-presentation">
                    <h2><a href="{% url 'novel:novel_content' xuanhuannovel.novelid %}">{{ xuanhuannovel.novelname }}</a></h2>
                    <p class="book-info">
                      <i></i>
                      <span>{{ xuanhuannovel.sort }}</span>
                      <span class="info-txt">{{ xuanhuannovel.state }}</span>
                      <span>{{ xuanhuannovel.type }}</span>
                    </p>
                    <p class="book-author">
                      <a href="javascript: void(0);">作者:
                        <span>{{ xuanhuannovel.author }}</span>
                      </a>
                    </p>
                    <p class="desc">
                      {{ xuanhuannovel.description|safe }}
                    </p>
                  </div>
                </div>
              </li>
              {% endfor %}

            </ul>
            
          </div>
        </div>





        <!-- Xuanhuan -->
        <div class="xuanhuan">
          <div class="xuanhuan-title">
            <span>武侠</span>
            <p class="txt">Martial arts</p>
            <p>novel</p>
            <span class="more"><a href="{% url 'novel:sort_list' 2 1 %}">更多<span style="float: right;font-size: 12px;letter-spacing: -2px;vertical-align: middle;margin-top: 2px;">&nbsp;&gt;&gt;</span></a></span>
          </div>
          <div class="wrap890 wuxia-wrap">

            <ul class="book-list">

              {% for wuxianovel in wuxianovels %}
              <li class="book">
                <div class="book-wrap">
                  <a class="cover" href="{% url 'novel:novel_content' wuxianovel.novelid %}"><img src="{{ wuxianovel.novelimg }}" alt="" width="136" height="180" /></a>
                  <div class="book-presentation">
                    <h2><a href="{% url 'novel:novel_content' wuxianovel.novelid %}">{{ wuxianovel.novelname }}</a></h2>
                    <p class="book-info">
                      <i></i>
                      <span>武侠</span>
                      <span class="info-txt">{{ wuxianovel.state }}</span>
                      <span>{{ wuxianovel.type }}</span>
                    </p>
                    <p class="book-author">
                      <a href="javascript: void(0);">作者:
                        <span>{{ wuxianovel.author }}</span>
                      </a>
                    </p>
                    <p class="desc">
                      {{ wuxianovel.description|safe }}
                    </p>
                  </div>
                </div>
              </li>
              {% endfor %}

            </ul>

          </div>
        </div>

      </div>
    </div>
  </div>
</section>
<!--===== Main End =====-->



<!--===== Begin Footer =====-->
<footer class="footer">
  <div class="wrap1000 footer-wrap">
    <div class="logo-footer">
      <a href="/">
        <img src="{% static 'img/footer_logo.png' %}" alt="" width="55" height="50" />
        <span class="footer-txt">潭州教育Python学院</span>
      </a>
      <span class="footer-font">
        TAN ZHOU EDU PYTHON COLLEGE
      </span>
    </div>
    <div class="copy-right">
      <p>
        本站小说均来源于互联网,仅供技术学习和交流使用,请尊重原创作者切勿用商业用途,请于下载后的24小时内删除。
      </p>
      <p class="">
        Copyright © 2017 All Rights Reserved 湖南潭州教育网络科技有限公司PYTHON学院 
      </p>
    </div>
  </div>
</footer>
<!--===== Footer End =====-->



<!-- Main Plugin -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>

</body>
</html>

novel/templates/more.html
{% load staticfiles %}
{% load i18n %}
<!doctype html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="Keywords" content="" />
    <meta name="description" content="" />
    <!-- <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" /> -->
    <title>Python探索馆 - Slice</title>
    <!-- Main Theme -->
    <link rel="stylesheet" href="{% static 'css/more.css' %}" />

    <!-- Font -->
    <link rel="stylesheet" href="http://at.alicdn.com/t/font_n5vylbuqe61or.css" />
  </head>
<body>


<!--===== Full Screen BG =====-->
<div class="full-pic"></div>



<!--===== Begin Header =====-->
<header class="header">
  <div class="fixed-head" style="position: fixed; width: 100%; background-color: #65b2f1; -webkit-transform: translateZ(0);">
    <div class="wrap1000 head-wrap">

      <div class="logo">
        <a href="/">
          Python学院图书馆
        </a>
      </div>

      <!-- nav -->
      <div class="nav">
        <ul class="nav-list">
          <li>
            <a href="/"><span>首页</span></a>
          </li>
          <li>
            <a href="{% url 'novel:sort_list' 1 1 %}"><span>玄幻</span></a>
          </li>
          <li>
            <a href="{% url 'novel:sort_list' 2 1 %}"><span>武侠</span></a>
          </li>
          <li>
            <a href="{% url 'novel:sort_list' 3 1 %}"><span>历史</span></a>
          </li>
          <li>
            <a href="{% url 'novel:sort_list' 4 1 %}"><span>言情</span></a>
          </li>
        </ul>
      </div><!-- ./nav -->

      <div class="search">
        <form action="{% url 'novel:search'%}" method="get" target="_blank">
          <input name="kw" placeholder="搜索书名" class="search-inp" type="text" maxlength="10" />
          <input id="search-submit-btn" type="submit" style="display: none;" />
          <label for="search-submit-btn">
            <i class="iconfont icon-search"></i>
          </label>
        </form>
      </div>

    </div><!-- /.wrap1000 -->
  </div>
</header>
<!--===== header End =====-->



<!--===== Begin Main =====-->
<section class="main">
  <div class="main-wrap wrap1000">
    <div class="hot-section">

      <!-- <div class="hot-shadow">
        <div class="hot-title">玄幻</div>
      </div> -->

      <div class="figure"></div>

      <div class="hot-content">

        <!-- Xuanhuan -->
        <h1 class="xunhuan-txt">{{ novelsort }}</h1>

        {% for novel in novels %}

        <div class="xuanhuan">
          <div class="wrap890 xuanhuan-wrap">

            <dl class="book-list">


              <dd class="book">
                <div class="book-border-bottom"></div>
                <div class="book-wrap">
                  <a class="cover" href="{% url 'novel:novel_content' novel.novelid %}"><img src="{{ novel.novelimg }}" alt="" width="102" height="136" /></a>
                  <div class="book-presentation">
                    <h2><a href="{% url 'novel:novel_content' novel.novelid %}">{{ novel.novelname }}</a></h2>
                    <p class="book-info">
                      <i></i>
                      <span>{{ novel.sort|safe }}</span>
                      <span class="info-txt">{{ novel.state }}</span>
                      <span>314.14万字</span>
                    </p>
                    <p class="book-author">
                      <a href="javascript: void(0);">作者:
                        <span>{{ novel.author }}</span>
                      </a>
                    </p>
                    <p class="desc" style="overflow: hidden; text-overflow: ellipsis; -webkit-box-orient: vertical; display: -webkit-box; -webkit-line-clamp: 5;">
                      {{ novel.description|safe|truncatechars:100 }}
                    </p>

                  </div>
                </div>
              </dd>


            </dl>
            
          </div>
        </div>
        {% endfor %}

        <!-- pagin -->
        <div class="pagin">
          <ul class="page-list">
              {% if novels.has_previous %}
                  <li><a href="{% url 'novel:sort_list' noveltype novels.previous_page_number %}"><<</a></li>
              {% endif %}

              {% if novels.has_next %}
                  <li><a href="{% url 'novel:sort_list' noveltype novels.next_page_number %}">>></a></li>
              {% endif %}
          </ul>

        </div>

      </div>
    </div>
  </div>
</section>
<!--===== Main End =====-->



<!--===== Begin Footer =====-->
<footer class="footer">
  <div class="wrap1000 footer-wrap">
    <div class="logo-footer">
      <a href="/">
        <img src="{% static 'img/footer_logo.png' %}" alt="" width="55" height="50" />
        <span class="footer-txt">潭州教育Python学院</span>
      </a>
      <span class="footer-font">
        TAN ZHOU EDU PYTHON COLLEGE
      </span>
    </div>
    <div class="copy-right">
      <p>
        本站小说均来源于互联网,仅供技术学习和交流使用,请尊重原创作者切勿用商业用途,请于下载后的24小时内删除。
      </p>
      <p class="">
        Copyright © 2017 All Rights Reserved 湖南潭州教育网络科技有限公司PYTHON学院 
      </p>
    </div>
  </div>
</footer>
<!--===== Footer End =====-->



<!-- Main Plugin -->
<script src="https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js"></script>
<script src="{% static 'js/index.js' %}"></script>

</body>
</html>               